[package]
name = "popper_codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
#mirage = { git = "https://github.com/popper-lang/mirage.git", branch = "main" }
mirage = { path = "../../../mirage" }
popper_ast = { path = "../popper_ast", features = ["extra-trait"] }